services:
  web:
    build: .
    ports:
      - "18898:18889"
    volumes:
      - ./env/test/project_cards.json:/app/project_cards.json
      - ./index.html:/app/index.html
      - ./project_timeline.html:/app/project_timeline.html
      - ./cardv8.html:/app/cardv8.html
    restart: unless-stopped
