services:
  web:
    build: .
    ports:
      - "18889:18889"
    volumes:
      - ./project_cards.json:/app/project_cards.json
      - ./index.html:/app/index.html
      - ./project_timeline.html:/app/project_timeline.html
      - ./cardv8.html:/app/cardv8.html
      - ./projects:/app/projects
      - ./reparse_v3.py:/app/reparse_v3.py
    restart: always
